"""trial uniqueness by run stage name

Revision ID: 568389289a95
Revises: 8c2363c84017
Create Date: 2026-09-21 13:01:14.091897
"""
from alembic import op
import sqlalchemy as sa


revision = '568389289a95'
down_revision = '8c2363c84017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trial_run_fingerprint_stage'), type_='unique')
        batch_op.create_unique_constraint('uq_trial_run_stage_name', ['run_id', 'stage', 'name', 'fingerprint'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trial_run_stage_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_trial_run_fingerprint_stage'), ['run_id', 'fingerprint', 'stage'])

    # ### end Alembic commands ###
