"""initial research record

Revision ID: 8c2363c84017
Revises: 
Create Date: 2026-09-21 12:59:34.584043
"""
import sqlalchemy as sa
from alembic import op

revision = '8c2363c84017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forward_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('config_sha', sa.String(length=32), nullable=False),
    sa.Column('topk', sa.Integer(), nullable=False),
    sa.Column('realised_return', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name', 'signal_date', 'strategy', name='uq_forward_date_strategy')
    )
    with op.batch_alter_table('forward_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forward_signals_config_name'), ['config_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_signals_signal_date'), ['signal_date'], unique=False)

    op.create_table('fundamentals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cik', sa.Integer(), nullable=False),
    sa.Column('adsh', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=96), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('filed', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'tag', 'period', 'filed', 'adsh', name='uq_fundamental_row')
    )
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamentals_cik'), ['cik'], unique=False)
        batch_op.create_index('ix_fundamentals_cik_tag_filed', ['cik', 'tag', 'filed'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamentals_filed'), ['filed'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamentals_tag'), ['tag'], unique=False)

    op.create_table('library_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('expr', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('sign', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ic_t', sa.Float(), nullable=True),
    sa.Column('dsr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name', 'name', name='uq_library_config_name')
    )
    with op.batch_alter_table('library_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_factors_config_name'), ['config_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_factors_status'), ['status'], unique=False)

    op.create_table('protocol_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_exceptions_config_name'), ['config_name'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('config_sha', sa.String(length=32), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_run_id'), ['run_id'], unique=True)

    op.create_table('trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_model', sa.String(length=64), nullable=False),
    sa.Column('prompt_sha', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('expr', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('sign', sa.Integer(), nullable=True),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('zoo_overlap', sa.Integer(), nullable=True),
    sa.Column('ic_mean', sa.Float(), nullable=True),
    sa.Column('ic_t', sa.Float(), nullable=True),
    sa.Column('ls_sharpe_ann', sa.Float(), nullable=True),
    sa.Column('dsr', sa.Float(), nullable=True),
    sa.Column('later_ic_mean', sa.Float(), nullable=True),
    sa.Column('n_trials_at_eval', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'fingerprint', 'stage', name='uq_trial_run_fingerprint_stage')
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trials_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_stage'), ['stage'], unique=False)
        batch_op.create_index('ix_trials_stage_status', ['stage', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_status'))
        batch_op.drop_index('ix_trials_stage_status')
        batch_op.drop_index(batch_op.f('ix_trials_stage'))
        batch_op.drop_index(batch_op.f('ix_trials_source'))
        batch_op.drop_index(batch_op.f('ix_trials_run_id'))
        batch_op.drop_index(batch_op.f('ix_trials_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_trials_family'))

    op.drop_table('trials')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_run_id'))

    op.drop_table('runs')
    with op.batch_alter_table('protocol_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_exceptions_config_name'))

    op.drop_table('protocol_exceptions')
    with op.batch_alter_table('library_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_factors_status'))
        batch_op.drop_index(batch_op.f('ix_library_factors_config_name'))

    op.drop_table('library_factors')
    with op.batch_alter_table('fundamentals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamentals_tag'))
        batch_op.drop_index(batch_op.f('ix_fundamentals_filed'))
        batch_op.drop_index('ix_fundamentals_cik_tag_filed')
        batch_op.drop_index(batch_op.f('ix_fundamentals_cik'))

    op.drop_table('fundamentals')
    with op.batch_alter_table('forward_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_signals_signal_date'))
        batch_op.drop_index(batch_op.f('ix_forward_signals_config_name'))

    op.drop_table('forward_signals')
    # ### end Alembic commands ###
