"""pre-registered hypotheses

Revision ID: 9d011d75fa42
Revises: 4002058acc4e
Create Date: 2026-09-21 22:56:56.614374
"""
from alembic import op
import sqlalchemy as sa


revision = '9d011d75fa42'
down_revision = '4002058acc4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('expr', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('sign', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name', 'content_sha', name='uq_hypothesis_content')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index('ix_hypotheses_config_created', ['config_name', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_config_name'), ['config_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_content_sha'), ['content_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_status'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_content_sha'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_config_name'))
        batch_op.drop_index('ix_hypotheses_config_created')

    op.drop_table('hypotheses')
    # ### end Alembic commands ###
